IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'test_table')
    DROP TABLE test_table
    
CREATE TABLE test_table(
    ID ID PRIMARY KEY NOT NULL,
    NAME NVARCHAR(30)
)
